files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mm_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 1F4424FCECB9B0E36962370306781E10
  logicalPath: config/pic32mm_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1F4424FCECB9B0E36962370306781E10
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config/pic32mm_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 229F88A1C12238B0348D9DB3225DF830
  logicalPath: config/pic32mm_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 229F88A1C12238B0348D9DB3225DF830
- generatedChecksum: 108DEB04DF62F7356A7A8D39A6697616
  logicalPath: config/pic32mm_curiosity/peripheral/crc
  name: plib_crc.c
  physicalPath: peripheral/crc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 108DEB04DF62F7356A7A8D39A6697616
- generatedChecksum: 71E5ACC69F93C73A5A6A0357AC92D694
  logicalPath: config/pic32mm_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71E5ACC69F93C73A5A6A0357AC92D694
- generatedChecksum: 3F5A6A320C8415B2BF1369204C587037
  logicalPath: config/pic32mm_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3F5A6A320C8415B2BF1369204C587037
- generatedChecksum: FD01D60309A8FEE878489EF78639963D
  logicalPath: config/pic32mm_curiosity/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: FD01D60309A8FEE878489EF78639963D
- generatedChecksum: CD1794BE8A9148BA4C835E811CBD7164
  logicalPath: config/pic32mm_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: CD1794BE8A9148BA4C835E811CBD7164
- generatedChecksum: 341294622A986EF08F96B0083762309D
  logicalPath: config/pic32mm_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 341294622A986EF08F96B0083762309D
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 76E5FDD4BAAEE0E06F4A1A6067F25397
  logicalPath: config/pic32mm_curiosity/peripheral/crc
  name: plib_crc.h
  physicalPath: peripheral/crc
  security: NON_SECURE
  type: HEADER
  userChecksum: 76E5FDD4BAAEE0E06F4A1A6067F25397
- generatedChecksum: F71A20BA61477D7082FBF03703A4CD38
  logicalPath: config/pic32mm_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F71A20BA61477D7082FBF03703A4CD38
- generatedChecksum: F693093204B64681BD415495886233C7
  logicalPath: config/pic32mm_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: F693093204B64681BD415495886233C7
- generatedChecksum: 9C14D01C2E2E7837B2A9FB7768E80A03
  logicalPath: config/pic32mm_curiosity/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 9C14D01C2E2E7837B2A9FB7768E80A03
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mm_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mm_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 3D141119C3B62A40C9963302D497B220
  logicalPath: config/pic32mm_curiosity
  name: p32MM0064GPL036.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 3D141119C3B62A40C9963302D497B220
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
