configName: pic32mm_curiosity
folderName: pic32mm_curiosity
format_version: v1.0
frameworkPath: ..\..\..\..\..\..\harmony_3
processor: PIC32MM0064GPL036
projectName: crc32_generate_pic32mm_curiosity
settings:
  PackageFilter: bootloader;bsp;core;csp;net;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MM_GPL_DFP\1.3.44\atdf\PIC32MM0064GPL036.atdf
