files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mm_usb_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 442CDEEE7F0FF64A304DD78E21D049D6
  logicalPath: config/pic32mm_usb_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 442CDEEE7F0FF64A304DD78E21D049D6
- generatedChecksum: D9EB6EFB36FD765BF3939E520BF75CF8
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D9EB6EFB36FD765BF3939E520BF75CF8
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: FE07C36C086699B2855BCDFB8F2F40EC
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: FE07C36C086699B2855BCDFB8F2F40EC
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mm_usb_curiosity/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: 7D2C3BA6E898D354234B66A2EB581B4D
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7D2C3BA6E898D354234B66A2EB581B4D
- generatedChecksum: 62BEF2F4682610E322DDECC47BBD17B3
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 62BEF2F4682610E322DDECC47BBD17B3
- generatedChecksum: 3395BC7859A61CF74BB26386EF635C14
  logicalPath: config/pic32mm_usb_curiosity/peripheral/rcon
  name: plib_rcon.c
  physicalPath: peripheral/rcon
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3395BC7859A61CF74BB26386EF635C14
- generatedChecksum: 294F464D30F83C24941CAAC097392571
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 294F464D30F83C24941CAAC097392571
- generatedChecksum: A215693A1ED38E97DBDF4AA6CB50727B
  logicalPath: config/pic32mm_usb_curiosity/peripheral/wdt
  name: plib_wdt.c
  physicalPath: peripheral/wdt
  security: NON_SECURE
  type: SOURCE
  userChecksum: A215693A1ED38E97DBDF4AA6CB50727B
- generatedChecksum: DB5D6981346A30FE7951D66DA5D8EB17
  logicalPath: config/pic32mm_usb_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB5D6981346A30FE7951D66DA5D8EB17
- generatedChecksum: 83B3B3A6CF081AC0E93E36B436ADD680
  logicalPath: config/pic32mm_usb_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 83B3B3A6CF081AC0E93E36B436ADD680
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_usb_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 95A377B239DD305CC8CD6D191A2C6D91
  logicalPath: config/pic32mm_usb_curiosity/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 95A377B239DD305CC8CD6D191A2C6D91
- generatedChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
- generatedChecksum: 4D047E06A19F9C27B8546FC9CCFAAEA5
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D047E06A19F9C27B8546FC9CCFAAEA5
- generatedChecksum: 3DB7963F65B11124653B2B4DE3C1604E
  logicalPath: config/pic32mm_usb_curiosity/peripheral/rcon
  name: plib_rcon.h
  physicalPath: peripheral/rcon
  security: NON_SECURE
  type: HEADER
  userChecksum: 3DB7963F65B11124653B2B4DE3C1604E
- generatedChecksum: 76D0274D98C0CD2504FA849177D55D6B
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 76D0274D98C0CD2504FA849177D55D6B
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: CE6EC097E60ED6A31224837752B229EF
  logicalPath: config/pic32mm_usb_curiosity/peripheral/wdt
  name: plib_wdt.h
  physicalPath: peripheral/wdt
  security: NON_SECURE
  type: HEADER
  userChecksum: CE6EC097E60ED6A31224837752B229EF
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mm_usb_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: C469F285BA2018DB29C8BEBCBE863C37
  logicalPath: config/pic32mm_usb_curiosity
  name: p32MM0256GPM064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C469F285BA2018DB29C8BEBCBE863C37
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
