files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mm_usb_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 60F3ADCA474B6795DCFC89FE9F8567DC
  logicalPath: config/pic32mm_usb_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 60F3ADCA474B6795DCFC89FE9F8567DC
- generatedChecksum: 03577CF637B7FD8A316F738905E5E994
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 03577CF637B7FD8A316F738905E5E994
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 908C9A6A0EFF9263FF4ACD957961B410
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp1.c
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 908C9A6A0EFF9263FF4ACD957961B410
- generatedChecksum: 886BF682EF0F34B1C27D0C2B1D8EA119
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp2.c
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 886BF682EF0F34B1C27D0C2B1D8EA119
- generatedChecksum: 8208D03C0D17B195074A0CE1988DB5FB
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp4.c
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8208D03C0D17B195074A0CE1988DB5FB
- generatedChecksum: E90DF69DD22D7C288D371BFD714AF4F9
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: E90DF69DD22D7C288D371BFD714AF4F9
- generatedChecksum: 63AB719E2216957F9829AD493B7B0FCD
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 63AB719E2216957F9829AD493B7B0FCD
- generatedChecksum: DFB3383158C5A7D8791312246B4EF10F
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: DFB3383158C5A7D8791312246B4EF10F
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mm_usb_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: FE71F1082EAF45D05DFEEE0B1E70157D
  logicalPath: config/pic32mm_usb_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FE71F1082EAF45D05DFEEE0B1E70157D
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_usb_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: C594C9C5478F86B8B12C6906570A5DD9
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp1.h
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: HEADER
  userChecksum: C594C9C5478F86B8B12C6906570A5DD9
- generatedChecksum: 821EA8F0601F683F6780468034578270
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp2.h
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: HEADER
  userChecksum: 821EA8F0601F683F6780468034578270
- generatedChecksum: E493AB8C3D2D2A3EAD92141E0B954304
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp4.h
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: HEADER
  userChecksum: E493AB8C3D2D2A3EAD92141E0B954304
- generatedChecksum: D37F856FC49464E0C02F0B7E27B8900A
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp_common.h
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: HEADER
  userChecksum: D37F856FC49464E0C02F0B7E27B8900A
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
- generatedChecksum: D0226D294D437AF5854104B8AD97C8CE
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D0226D294D437AF5854104B8AD97C8CE
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mm_usb_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: C469F285BA2018DB29C8BEBCBE863C37
  logicalPath: config/pic32mm_usb_curiosity
  name: p32MM0256GPM064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C469F285BA2018DB29C8BEBCBE863C37
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
