files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mm_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 92BE9D4C2A7CDBEB344766E098C23363
  logicalPath: config/pic32mm_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 92BE9D4C2A7CDBEB344766E098C23363
- generatedChecksum: BCD701A8C9F3E3DAE35ECD86F80B7747
  logicalPath: config/pic32mm_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: BCD701A8C9F3E3DAE35ECD86F80B7747
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mm_curiosity.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: EAF4218359D15FCD360FE7E5EBBA6D51
  logicalPath: config/pic32mm_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: EAF4218359D15FCD360FE7E5EBBA6D51
- generatedChecksum: 579C2FB4CA22594ABFD878B72CB394EA
  logicalPath: config/pic32mm_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 579C2FB4CA22594ABFD878B72CB394EA
- generatedChecksum: B280ACD40276625E78D5DB3A88C318DC
  logicalPath: config/pic32mm_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: B280ACD40276625E78D5DB3A88C318DC
- generatedChecksum: 49936708A2CD8CE506DE4D74428BA91C
  logicalPath: config/pic32mm_curiosity/peripheral/spi/spi_master
  name: plib_spi2_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 49936708A2CD8CE506DE4D74428BA91C
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mm_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: F0388B89CE4C8C1987C7E416FF923B0C
  logicalPath: config/pic32mm_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F0388B89CE4C8C1987C7E416FF923B0C
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: F71A20BA61477D7082FBF03703A4CD38
  logicalPath: config/pic32mm_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F71A20BA61477D7082FBF03703A4CD38
- generatedChecksum: E74A1CA7C7F8CF835E01A88D647F0DCE
  logicalPath: config/pic32mm_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: E74A1CA7C7F8CF835E01A88D647F0DCE
- generatedChecksum: DD36DE6ACD8AE29EFBB17C8C6B4E962E
  logicalPath: config/pic32mm_curiosity/peripheral/spi/spi_master
  name: plib_spi2_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: DD36DE6ACD8AE29EFBB17C8C6B4E962E
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/pic32mm_curiosity/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mm_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: EBD6E51AC74F4B4A4AC25BE63E43F94C
  logicalPath: config/pic32mm_curiosity
  name: p32MM0064GPL036.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: EBD6E51AC74F4B4A4AC25BE63E43F94C
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
