configName: pic32mm_curiosity
folderName: pic32mm_curiosity
format_version: v1.0
frameworkPath: ..\..\..\..\..\..
processor: PIC32MM0064GPL036
projectName: spi_write_read_test_app_pic32mm_curiosity
settings:
  PackageFilter: bootloader;bootloader_apps_i2c;bootloader_apps_usb;bsp;core;crypto;crypto_apps_encrypt_decrypt;csp;csp_apps_pic32mk;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MM_GPL_DFP\1.3.44\atdf\PIC32MM0064GPL036.atdf
