files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mm_usb_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 445B750D2C9FD4E8828D22D2E4D33340
  logicalPath: config/pic32mm_usb_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 445B750D2C9FD4E8828D22D2E4D33340
- generatedChecksum: 03EA6DF221295FA280762AF44969D2D1
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 03EA6DF221295FA280762AF44969D2D1
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: A0E54EEB823AC86EC0FA27ACD75F539A
  logicalPath: config/pic32mm_usb_curiosity/peripheral/adc
  name: plib_adc.c
  physicalPath: peripheral/adc
  security: NON_SECURE
  type: SOURCE
  userChecksum: A0E54EEB823AC86EC0FA27ACD75F539A
- generatedChecksum: 29EF98FB76BC07852AD9D1CAB26B306C
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 29EF98FB76BC07852AD9D1CAB26B306C
- generatedChecksum: 2983822C498764AAD109817306554ADA
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2983822C498764AAD109817306554ADA
- generatedChecksum: 1CA3492EA27CFC845CBC168052688228
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1CA3492EA27CFC845CBC168052688228
- generatedChecksum: 294F464D30F83C24941CAAC097392571
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 294F464D30F83C24941CAAC097392571
- generatedChecksum: DB5D6981346A30FE7951D66DA5D8EB17
  logicalPath: config/pic32mm_usb_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB5D6981346A30FE7951D66DA5D8EB17
- generatedChecksum: F9DAD08FEAC3ED746CE192C0EFA9F684
  logicalPath: config/pic32mm_usb_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F9DAD08FEAC3ED746CE192C0EFA9F684
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_usb_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: B89C020C44D0531D602068641E4FE18C
  logicalPath: config/pic32mm_usb_curiosity/peripheral/adc
  name: plib_adc.h
  physicalPath: peripheral/adc
  security: NON_SECURE
  type: HEADER
  userChecksum: B89C020C44D0531D602068641E4FE18C
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
- generatedChecksum: 76F98F5D5ED4C2833AE90CDE124BBE1B
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 76F98F5D5ED4C2833AE90CDE124BBE1B
- generatedChecksum: 76D0274D98C0CD2504FA849177D55D6B
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 76D0274D98C0CD2504FA849177D55D6B
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mm_usb_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 85BC9F07F0C6F33EA64CEE00CB73E55D
  logicalPath: config/pic32mm_usb_curiosity
  name: p32MM0256GPM064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 85BC9F07F0C6F33EA64CEE00CB73E55D
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
