format_version: v1.0
type: UniqueComponent
attributes: {id: cdac1}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: CDAC_REFSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
- type: ElementPosition
  attributes: {x: '29', y: '60', id: cdac1}
