format_version: v1.0
type: UniqueComponent
attributes: {id: cmp}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: CMP_1_CON_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: cmp, value: '0'}
  - type: KeyValueSet
    attributes: {id: CMP_2_CON_CCH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: CMP_2_CON_CREF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: CMP_2_CON_EVPOL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Hex
    attributes: {id: CMP_2_CON_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: cmp, value: '80'}
  - type: KeyValueSet
    attributes: {id: CMP_CMSTAT_CVREFSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Hex
    attributes: {id: CMP_CMSTAT_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: cmp, value: '256'}
- type: ElementPosition
  attributes: {x: '320', y: '20', id: cmp}
