files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mm_usb_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: D4AF8AE59C314B5CDDD1367124C8AA05
  logicalPath: config/pic32mm_usb_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D4AF8AE59C314B5CDDD1367124C8AA05
- generatedChecksum: DF4FDCA48FF3E50233754D4E363F48C9
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DF4FDCA48FF3E50233754D4E363F48C9
- generatedChecksum: F81A00E640818EDFB9E79C9BD241AEF4
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: F81A00E640818EDFB9E79C9BD241AEF4
- generatedChecksum: 98E2EECAB2E2144092200FD0262E1EA6
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 98E2EECAB2E2144092200FD0262E1EA6
- generatedChecksum: E19AE62EF1F5C36E4ECE56386A14C04F
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: E19AE62EF1F5C36E4ECE56386A14C04F
- generatedChecksum: 1CA3492EA27CFC845CBC168052688228
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1CA3492EA27CFC845CBC168052688228
- generatedChecksum: E4C85B79BE9390792EEFDD2344811A93
  logicalPath: config/pic32mm_usb_curiosity/peripheral/rtcc
  name: plib_rtcc.c
  physicalPath: peripheral/rtcc
  security: NON_SECURE
  type: SOURCE
  userChecksum: E4C85B79BE9390792EEFDD2344811A93
- generatedChecksum: 294F464D30F83C24941CAAC097392571
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 294F464D30F83C24941CAAC097392571
- generatedChecksum: DB5D6981346A30FE7951D66DA5D8EB17
  logicalPath: config/pic32mm_usb_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB5D6981346A30FE7951D66DA5D8EB17
- generatedChecksum: 4209E6E08B122E7F72813659339C332A
  logicalPath: config/pic32mm_usb_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4209E6E08B122E7F72813659339C332A
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_usb_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
- generatedChecksum: 76F98F5D5ED4C2833AE90CDE124BBE1B
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 76F98F5D5ED4C2833AE90CDE124BBE1B
- generatedChecksum: 0A4995F0AEBD0733D8972FC0F6F8F247
  logicalPath: config/pic32mm_usb_curiosity/peripheral/rtcc
  name: plib_rtcc.h
  physicalPath: peripheral/rtcc
  security: NON_SECURE
  type: HEADER
  userChecksum: 0A4995F0AEBD0733D8972FC0F6F8F247
- generatedChecksum: 76D0274D98C0CD2504FA849177D55D6B
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 76D0274D98C0CD2504FA849177D55D6B
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mm_usb_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 85BC9F07F0C6F33EA64CEE00CB73E55D
  logicalPath: config/pic32mm_usb_curiosity
  name: p32MM0256GPM064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 85BC9F07F0C6F33EA64CEE00CB73E55D
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
