format_version: v1.0
type: UniqueComponent
attributes: {id: ccp2}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: CCPCON1_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ccp2, value: '3'}
  - type: Hex
    attributes: {id: CCPCON2_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ccp2, value: '67108864'}
  - type: Hex
    attributes: {id: CCPCON3_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ccp2, value: '0'}
  - type: File
    attributes: {id: CCP_CAPTURE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: CCP_CAPTURE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: CCP_COMPARE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: CCP_COMPARE_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: CCP_COMPARE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: CCP_COMP_CCPCON1_MOD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: CCP_COMP_CCPCON2_OCCEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Combo
    attributes: {id: CCP_OPERATION_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Compare}
  - type: File
    attributes: {id: CCP_TIMER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: CCP_TIMER_INTERRUPT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Menu
    attributes: {id: CCP_TIMER_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: CCP_TIMER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '461', y: '18', id: ccp2}
