files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mm_usb_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: FBE77E7066BB48929F11A06EA6297DB8
  logicalPath: config/pic32mm_usb_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: FBE77E7066BB48929F11A06EA6297DB8
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 82C8362006E5F8E0C3BF333B3CA6FDB9
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp1.c
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 82C8362006E5F8E0C3BF333B3CA6FDB9
- generatedChecksum: 0EB96F4DE3EC227D8E2827DB07C9D6C6
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp2.c
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0EB96F4DE3EC227D8E2827DB07C9D6C6
- generatedChecksum: AD50CE34DC374F5CDD3B82ED229EAA17
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: AD50CE34DC374F5CDD3B82ED229EAA17
- generatedChecksum: 71E5ACC69F93C73A5A6A0357AC92D694
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71E5ACC69F93C73A5A6A0357AC92D694
- generatedChecksum: 8B5AB6DACCD1C3B75495105186856519
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8B5AB6DACCD1C3B75495105186856519
- generatedChecksum: 294F464D30F83C24941CAAC097392571
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 294F464D30F83C24941CAAC097392571
- generatedChecksum: DB5D6981346A30FE7951D66DA5D8EB17
  logicalPath: config/pic32mm_usb_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB5D6981346A30FE7951D66DA5D8EB17
- generatedChecksum: 74ABAAE3A5DA7ECF022EAE027D995A09
  logicalPath: config/pic32mm_usb_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 74ABAAE3A5DA7ECF022EAE027D995A09
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_usb_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: B0BE31A09FBE103BF4E262FAD980439A
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp1.h
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: HEADER
  userChecksum: B0BE31A09FBE103BF4E262FAD980439A
- generatedChecksum: CB3D6D63B320F245ECBCDAF08914C144
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp2.h
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: HEADER
  userChecksum: CB3D6D63B320F245ECBCDAF08914C144
- generatedChecksum: D37F856FC49464E0C02F0B7E27B8900A
  logicalPath: config/pic32mm_usb_curiosity/peripheral/ccp
  name: plib_ccp_common.h
  physicalPath: peripheral/ccp
  security: NON_SECURE
  type: HEADER
  userChecksum: D37F856FC49464E0C02F0B7E27B8900A
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
- generatedChecksum: D0226D294D437AF5854104B8AD97C8CE
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D0226D294D437AF5854104B8AD97C8CE
- generatedChecksum: 76D0274D98C0CD2504FA849177D55D6B
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 76D0274D98C0CD2504FA849177D55D6B
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mm_usb_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: C469F285BA2018DB29C8BEBCBE863C37
  logicalPath: config/pic32mm_usb_curiosity
  name: p32MM0256GPM064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C469F285BA2018DB29C8BEBCBE863C37
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
