files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mm_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: FDE9819E48D032974B66834DC70C0109
  logicalPath: config/pic32mm_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: FDE9819E48D032974B66834DC70C0109
- generatedChecksum: B63E3CBE0BEDB8AB5DD58BC222FBBE86
  logicalPath: config/pic32mm_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B63E3CBE0BEDB8AB5DD58BC222FBBE86
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 4230B954B272A1920698464AE7E55D03
  logicalPath: config/pic32mm_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4230B954B272A1920698464AE7E55D03
- generatedChecksum: B2BF007ACFE61D47BDF5C1304B05A6B3
  logicalPath: config/pic32mm_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: B2BF007ACFE61D47BDF5C1304B05A6B3
- generatedChecksum: 635E8A4AF1F5A0EA65BE755BF7EE00A6
  logicalPath: config/pic32mm_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 635E8A4AF1F5A0EA65BE755BF7EE00A6
- generatedChecksum: 36D9DCE22AA293F8B0244EC40F9041D7
  logicalPath: config/pic32mm_curiosity/peripheral/spi/spi_slave
  name: plib_spi2_slave.c
  physicalPath: peripheral/spi/spi_slave
  security: NON_SECURE
  type: SOURCE
  userChecksum: 36D9DCE22AA293F8B0244EC40F9041D7
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mm_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 6B7B617FC787651D6D2A29094431A06A
  logicalPath: config/pic32mm_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 6B7B617FC787651D6D2A29094431A06A
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: F71A20BA61477D7082FBF03703A4CD38
  logicalPath: config/pic32mm_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F71A20BA61477D7082FBF03703A4CD38
- generatedChecksum: 28E347481F8B66AED68D747EEA36E006
  logicalPath: config/pic32mm_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 28E347481F8B66AED68D747EEA36E006
- generatedChecksum: 18440BD948A99544D61882F35C917F52
  logicalPath: config/pic32mm_curiosity/peripheral/spi/spi_slave
  name: plib_spi2_slave.h
  physicalPath: peripheral/spi/spi_slave
  security: NON_SECURE
  type: HEADER
  userChecksum: 18440BD948A99544D61882F35C917F52
- generatedChecksum: 0314BA0C96E3C76CC27841DFD86493E1
  logicalPath: config/pic32mm_curiosity/peripheral/spi/spi_slave
  name: plib_spi_slave_common.h
  physicalPath: peripheral/spi/spi_slave
  security: NON_SECURE
  type: HEADER
  userChecksum: 0314BA0C96E3C76CC27841DFD86493E1
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mm_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 3D141119C3B62A40C9963302D497B220
  logicalPath: config/pic32mm_curiosity
  name: p32MM0064GPL036.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 3D141119C3B62A40C9963302D497B220
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
