files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mm_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: DC42BD74101586661A0A428F4C03F7E0
  logicalPath: config/pic32mm_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DC42BD74101586661A0A428F4C03F7E0
- generatedChecksum: 470F7009E07245C19402DA642CD24C5D
  logicalPath: config/pic32mm_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 470F7009E07245C19402DA642CD24C5D
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mm_curiosity.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 4796BD564AB4E0C7261852B22C2B083B
  logicalPath: config/pic32mm_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4796BD564AB4E0C7261852B22C2B083B
- generatedChecksum: 10345E4D63C9FB0324402CDAF70B0DEE
  logicalPath: config/pic32mm_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 10345E4D63C9FB0324402CDAF70B0DEE
- generatedChecksum: 1E9242FE3EE68629D9EFF1A9A922C2C5
  logicalPath: config/pic32mm_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1E9242FE3EE68629D9EFF1A9A922C2C5
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mm_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: B1EE48A69E75E954BB87BBE783823F42
  logicalPath: config/pic32mm_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: B1EE48A69E75E954BB87BBE783823F42
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: F71A20BA61477D7082FBF03703A4CD38
  logicalPath: config/pic32mm_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F71A20BA61477D7082FBF03703A4CD38
- generatedChecksum: 90DF36721228B43390826FB65467F95D
  logicalPath: config/pic32mm_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 90DF36721228B43390826FB65467F95D
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mm_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: 4DDCE5162E217B3B5C5F04437A6D5FB1
  logicalPath: config/pic32mm_curiosity
  name: p32MM0064GPL036.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 4DDCE5162E217B3B5C5F04437A6D5FB1
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
