files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mm_usb_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 2C9AA6441AB458A18F64B5CE9E93406D
  logicalPath: config/pic32mm_usb_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2C9AA6441AB458A18F64B5CE9E93406D
- generatedChecksum: 2FF667701C75A8D18DDDA99B651C2312
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2FF667701C75A8D18DDDA99B651C2312
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 85F51EC7262BE41380F3DBA49DF57471
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 85F51EC7262BE41380F3DBA49DF57471
- generatedChecksum: 5B05AF9CBC4F016ADAE5E07734A2F28E
  logicalPath: config/pic32mm_usb_curiosity/peripheral/dmac
  name: plib_dmac.c
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5B05AF9CBC4F016ADAE5E07734A2F28E
- generatedChecksum: B0D4FEC907FDD3BC8F3CB07796B5C44D
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: B0D4FEC907FDD3BC8F3CB07796B5C44D
- generatedChecksum: 82BED06E5FF3CBB9A5400C90F2C3EC13
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 82BED06E5FF3CBB9A5400C90F2C3EC13
- generatedChecksum: 294F464D30F83C24941CAAC097392571
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 294F464D30F83C24941CAAC097392571
- generatedChecksum: DB5D6981346A30FE7951D66DA5D8EB17
  logicalPath: config/pic32mm_usb_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB5D6981346A30FE7951D66DA5D8EB17
- generatedChecksum: 32F6A799DCB47564C7462E55CC1E1D2A
  logicalPath: config/pic32mm_usb_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 32F6A799DCB47564C7462E55CC1E1D2A
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_usb_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 044A6F7964F68A977E26A257A31D6C2C
  logicalPath: config/pic32mm_usb_curiosity/peripheral/dmac
  name: plib_dmac.h
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: 044A6F7964F68A977E26A257A31D6C2C
- generatedChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
- generatedChecksum: C122A700F4589958380EA91526466AA3
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: C122A700F4589958380EA91526466AA3
- generatedChecksum: 76D0274D98C0CD2504FA849177D55D6B
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 76D0274D98C0CD2504FA849177D55D6B
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mm_usb_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 85BC9F07F0C6F33EA64CEE00CB73E55D
  logicalPath: config/pic32mm_usb_curiosity
  name: p32MM0256GPM064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 85BC9F07F0C6F33EA64CEE00CB73E55D
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
