format_version: v1.0
type: UniqueComponent
attributes: {id: clc1}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: CLC_DS1_OUTPUT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: KeyValueSet
    attributes: {id: CLC_DS3_OUTPUT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: Boolean
    attributes: {id: CLC_GATE1_DS1_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: CLC_GATE3_DS3_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: CLC_LOGIC_CELL_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: CLC_LOGIC_CELL_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Boolean
    attributes: {id: CLC_LOGIC_CELL_OUTPUT_POLARITY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: CLC_PORT_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '320', y: '19', id: clc1}
